### ISSUE TITLE
Buttons Fail to Start MN, Must Use Debug Window commands

### ISSUE THREAD

**Issue by Dark-Jedi** [CooleRRSA/crave-ng#2] opened 2018-01-11 23:46 UTC
Using Win 32 2.5.0.1. Followed the guide for local all. Tried starting the MNs using the buttons (start all, start missing, etc) and each time it threw an IP address error.  I knew the IP address / port forwarding was not an issue because I was running the previous crave with the same port and settings.  But when I used the debug window to start the masternode, it started successfully.  So there must be some bug in the code associated with the button GUI.

**Comment by CooleRRSA** [comment] 2018-01-12 08:10
Thank you. Yes. It's known issue.
It happens sometimes because wallet can't detect that IPV4 network is available.
Hard to reproduce this bug in testing facility but will be fixed anyway.

**Closed** 2018-01-12 13:34 UTC
